import { CalendarDays, Clock3, Copy, Download, Edit3, FileCheck2, Share2, Trash2 } from "lucide-react";
import { Button } from "@/src/components/ui/button";
import { Card, CardContent, CardHeader } from "@/src/components/ui/card";
import { SignaturePreview } from "@/src/components/ui/signature-preview";
import { SignatureStatusBadge } from "@/src/components/ui/status-badge";
import { mockSignatures } from "@/src/lib/mock-data";

export default async function SignatureDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const signature = mockSignatures.find(item => item.id === id) ?? mockSignatures[0];
  return <div><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-slate-500">Signature profile</p><h1 className="mt-1 text-3xl font-semibold">{signature.name}</h1></div><div className="flex flex-wrap gap-2"><Button variant="secondary"><Copy className="h-4 w-4" /> Copy Signature</Button><Button variant="secondary"><Edit3 className="h-4 w-4" /> Customize</Button><Button variant="secondary"><Download className="h-4 w-4" /> Export</Button><Button variant="secondary"><Share2 className="h-4 w-4" /> Share</Button><Button variant="danger"><Trash2 className="h-4 w-4" /> Delete</Button></div></div><div className="mt-8 grid gap-6 xl:grid-cols-[1fr_.75fr]"><Card><CardHeader><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Signature preview</p><h2 className="mt-1 text-lg font-semibold">Visual representation</h2></div><SignatureStatusBadge status={signature.status} /></CardHeader><CardContent><SignaturePreview signature={signature.signature} className="min-h-48" /></CardContent></Card><Card><CardHeader><h2 className="font-semibold">Details</h2></CardHeader><CardContent className="space-y-5">{[{ label: "Category", value: signature.category }, { label: "Created", value: signature.createdAt }, { label: "Last modified", value: signature.lastModified }, { label: "Style", value: signature.style }, { label: "Expiration", value: signature.expiresAt }, { label: "Usage", value: "Available to copy and export" }].map(item => <div key={item.label} className="flex items-start justify-between gap-4 border-b border-slate-100 pb-4 last:border-0 last:pb-0"><span className="text-sm text-slate-500">{item.label}</span><span className="text-right text-sm font-medium">{item.value}</span></div>)}</CardContent></Card></div><Card className="mt-6"><CardHeader><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Security information</p><h2 className="mt-1 text-lg font-semibold">Signature status</h2></div><FileCheck2 className="h-5 w-5 text-emerald-600" /></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><Clock3 className="h-4 w-4 text-slate-500" /><p className="mt-3 text-sm font-medium">Expiration</p><p className="mt-1 text-xs text-slate-500">{signature.expiresAt}</p></div><div className="rounded-xl bg-slate-50 p-4"><CalendarDays className="h-4 w-4 text-slate-500" /><p className="mt-3 text-sm font-medium">Version control</p><p className="mt-1 text-xs text-slate-500">{signature.versions.length} versions saved</p></div><div className="rounded-xl bg-slate-50 p-4"><FileCheck2 className="h-4 w-4 text-slate-500" /><p className="mt-3 text-sm font-medium">Usage</p><p className="mt-1 text-xs text-slate-500">Ready for supported actions</p></div></CardContent></Card></div>;
}
