"use client";

import { Copy, RotateCcw, SlidersHorizontal, Type } from "lucide-react";
import { Button } from "@/src/components/ui/button";
import { SignaturePreview } from "@/src/components/ui/signature-preview";
import { useState } from "react";

export default function SignatureDesignerPage() {
  const [size, setSize] = useState(30);
  const [spacing, setSpacing] = useState(4);
  const [slant, setSlant] = useState(-2);
  return <div><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-slate-500">Professional · Version 2</p><h1 className="mt-1 text-3xl font-semibold">Signature designer</h1><p className="mt-2 text-sm text-slate-600">Customize the visual representation of your signature.</p></div><div className="flex gap-2"><Button variant="secondary"><RotateCcw className="h-4 w-4" /> Reset</Button><Button><Copy className="h-4 w-4" /> Copy</Button></div></div><div className="mt-8 grid gap-6 xl:grid-cols-[1fr_360px]"><section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><p className="font-semibold">Live preview</p><span className="text-xs text-slate-500">Visual only</span></div><div className="mt-5 rounded-2xl bg-slate-50 p-8"><SignaturePreview signature="Paul Ogini" className="min-h-48" /></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium text-slate-700">Signature text<input className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 outline-none focus:border-blue-600" defaultValue="Paul Ogini" /></label><label className="block text-sm font-medium text-slate-700">Font style<select className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 outline-none"><option>Elegant serif</option><option>Modern sans</option><option>Classic handwritten</option></select></label></div></section><aside className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-center gap-2 font-semibold"><SlidersHorizontal className="h-4 w-4" /> Appearance</div><div className="mt-6 space-y-6">{[{ label: "Size", value: size, min: 16, max: 44, setter: setSize }, { label: "Spacing", value: spacing, min: 0, max: 10, setter: setSpacing }, { label: "Slant", value: slant, min: -8, max: 8, setter: setSlant }].map(({ label, value, min, max, setter }) => <label key={label} className="block text-sm font-medium"><span className="flex justify-between text-slate-700"><span>{label}</span><span className="text-slate-400">{value}</span></span><input aria-label={label} type="range" min={min} max={max} value={value} onChange={(event) => setter(Number(event.target.value))} className="mt-3 w-full accent-slate-950" /></label>)}</div><div className="mt-7 border-t border-slate-100 pt-5"><p className="text-xs leading-5 text-slate-500">Changes create a new visual version. They do not create a cryptographic signature.</p><Button className="mt-5 w-full"><Type className="h-4 w-4" /> Save Version</Button></div></aside></div></div>;
}
