import { Activity, Fingerprint, KeyRound, LockKeyhole, ShieldCheck } from "lucide-react";
import { Button } from "@/src/components/ui/button";
import { Card, CardContent, CardHeader } from "@/src/components/ui/card";

const securityRows = [{ title: "Change PIN", detail: "Manage your vault PIN", icon: KeyRound, action: "Change" }, { title: "Biometric Unlock", detail: "Use device authentication when supported", icon: Fingerprint, action: "Enable" }, { title: "Auto-lock", detail: "Control vault session timeout", icon: LockKeyhole, action: "Configure" }, { title: "Active sessions", detail: "Review your current sessions", icon: Activity, action: "Review" }];

export default function SecurityPage() {
  return <div><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-slate-500">Vault control</p><h1 className="mt-1 text-3xl font-semibold">Security</h1><p className="mt-2 text-sm text-slate-600">Protect your signature vault and review its current state.</p></div><Button variant="secondary"><ShieldCheck className="h-4 w-4" /> Security status</Button></div><Card className="mt-8"><CardHeader><div><p className="text-xs font-semibold uppercase tracking-wider text-emerald-600">Protected</p><h2 className="mt-1 text-lg font-semibold">Vault protection status</h2></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><ShieldCheck className="h-5 w-5" /></span></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-2">{securityRows.map(({ title, detail, icon: Icon, action }) => <div key={title} className="flex items-center gap-4 rounded-xl border border-slate-200 p-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-600"><Icon className="h-5 w-5" /></span><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div><button className="text-xs font-semibold text-blue-700">{action}</button></div>)}</div></CardContent></Card><Card className="mt-5"><CardHeader><h2 className="font-semibold">Privacy-aware controls</h2></CardHeader><CardContent><p className="text-sm leading-6 text-slate-600">This interface demonstrates secure settings and mock controls. No authentication or device API is connected yet.</p></CardContent></Card></div>;
}
