import Link from "next/link";
import { ArrowLeft, Check, Palette, Type } from "lucide-react";
import { Button } from "@/src/components/ui/button";
import { Field, Input, Select } from "@/src/components/ui/form-controls";
import { SignaturePreview } from "@/src/components/ui/signature-preview";

export default function NewSignaturePage() {
  return <div><Link href="/vault" className="mb-4 inline-flex items-center gap-2 text-sm text-slate-500 hover:text-slate-950"><ArrowLeft className="h-4 w-4" /> Back to vault</Link><h1 className="text-3xl font-semibold tracking-tight">Create a signature</h1><p className="mt-2 text-sm text-slate-600">Choose a name, style, and signature text. You can refine the result before saving.</p><div className="mt-8 grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><form className="space-y-5 rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><Field label="Signature name"><Input placeholder="e.g. Professional" /></Field><Field label="Signature text"><Input placeholder="Your full name or initials" /></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="Category"><Select defaultValue="professional"><option value="professional">Professional</option><option value="personal">Personal</option><option value="business">Business</option></Select></Field><Field label="Style"><Select defaultValue="elegant"><option value="classic">Classic</option><option value="elegant">Elegant</option><option value="modern">Modern</option><option value="minimal">Minimal</option></Select></Field></div><fieldset><legend className="mb-3 text-sm font-medium text-slate-700">Choose a style</legend><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{["Classic", "Elegant", "Modern", "Minimal"].map((style, index) => <button type="button" key={style} className={`rounded-xl border p-3 text-left text-xs ${index === 1 ? "border-blue-600 bg-blue-50 text-blue-700" : "border-slate-200 hover:border-slate-400"}`}><span className="mb-2 block text-lg font-serif">{style === "Classic" ? "A" : style === "Elegant" ? "J" : style === "Modern" ? "A." : "JD"}</span>{style}</button>)}</div></fieldset><div className="flex flex-col gap-2 border-t border-slate-100 pt-5 sm:flex-row sm:justify-end"><Button variant="ghost">Cancel</Button><Button type="submit"><Check className="h-4 w-4" /> Create Signature</Button></div></form><section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Live preview</p><p className="mt-1 text-xs text-slate-500">Visual representation only</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-600">Elegant</span></div><div className="mt-6"><SignaturePreview signature="Jolomi Dudu" /></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-slate-200 p-4"><Type className="h-4 w-4 text-slate-500" /><p className="mt-3 text-sm font-medium">Signature text</p><p className="mt-1 text-xs text-slate-500">Your stored signature text</p></div><div className="rounded-xl border border-slate-200 p-4"><Palette className="h-4 w-4 text-slate-500" /><p className="mt-3 text-sm font-medium">Appearance</p><p className="mt-1 text-xs text-slate-500">Style-specific preview only</p></div></div></section></div></div>;
}
